### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by Akramx15** [BeboKhouja/ADB-GUI#1]
![image](https://github.com/BeboKhouja/ADB-GUI/assets/149894533/e27dd622-9739-4f4b-91e5-6b080bf116cb)

**Comment by BeboKhouja** [comment]
?

**Comment by BeboKhouja** [comment]
Thats because, it relies on adb being on $PATH.

**Comment by BeboKhouja** [comment]
Try launching it from the command line
